apiVersion: v1
kind: apiVersion: v1
kind: Pod
metadata:
  name: primeiro-pod
  labels:
    app.kubernetes.io/name: primeiro-pod
spec:
  containers:
  - name: primeiro-pod
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
